package comx.y.z.collage.constance


const val PREF_THEME_ID = "PREF_THEME_ID"
const val PREF_SHOW_RATE = "PREF_SHOW_RATE"
const val PREF_APP_VERSION ="PREF_APP_VERSION"
const val PREF_FIRST_TIME_INSTALL_APP = "PREF_FIRST_TIME_INSTALL_APP"
const val PREF_COUNT_OPEN_APP = "PREF_COUNT_OPEN_APP"